version: '3.8'

services:
  web:
    build: ./app
    ports:
      - "${APP_PORT}:5000"
    depends_on:
      - redis
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
